(() => {
  'use strict';
  const APP = document.getElementById('app');
  const ASSET = 'assets/';
  const DATA = {
    animals: [
      ['cat','Kucing','animals/cat.svg','Meong!'],['dog','Anjing','animals/dog.svg','Guk guk!'],['rabbit','Kelinci','animals/rabbit.svg','Cuit cuit!'],
      ['cow','Sapi','animals/cow.svg','Moo!'],['chicken','Ayam','animals/chicken.svg','Kukuruyuk!'],['elephant','Gajah','animals/elephant.svg','Pruuut!']
    ].map(([id,name,img,sound])=>({id,name,img,sound})),
    fruits: [
      ['apple','Apel','🍎'],['banana','Pisang','🍌'],['orange','Jeruk','🍊'],['watermelon','Semangka','🍉'],['strawberry','Stroberi','🍓'],['mango','Mangga','🥭']
    ].map(([id,name,emoji])=>({id,name,emoji})),
    shapes: [
      ['circle','Lingkaran','circle'],['square','Persegi','square'],['triangle','Segitiga','triangle'],['star','Bintang','star'],['rectangle','Persegi panjang','rectangle'],['heart','Hati','heart']
    ].map(([id,name,type])=>({id,name,type}))
  };
  const WORLDS = [
    {id:'animals',name:'Dunia Hewan',desc:'Kenalan dan bermain bersama hewan.',icon:'🐾'},
    {id:'fruits',name:'Dunia Buah',desc:'Kenali buah lewat warna dan bentuk.',icon:'🍎'},
    {id:'shapes',name:'Dunia Bentuk',desc:'Temukan bentuk di sekitar kita.',icon:'⭐'}
  ];
  const ACTIVITIES = {
    animals:[['find','Cari Hewan','Dengar lalu pilih hewan yang benar.','🔎'],['match','Pasangkan Hewan','Temukan dua hewan yang sama.','🧩']],
    fruits:[['find','Cari Buah','Dengar lalu pilih buah yang benar.','🔎'],['match','Pasangkan Buah','Temukan dua buah yang sama.','🧩']],
    shapes:[['find','Cari Bentuk','Dengar lalu pilih bentuk yang benar.','🔎'],['match','Pasangkan Bentuk','Temukan dua bentuk yang sama.','🧩']]
  };
  const state={screen:'home',world:null,activity:null,round:0,total:5,target:null,options:[],locked:false,audio:true,selected:null,matched:[]};
  try{state.audio=localStorage.getItem('tm-audio')!=='0'}catch{}

  function saveAudio(){try{localStorage.setItem('tm-audio',state.audio?'1':'0')}catch{}}
  function speak(text){if(!state.audio||!('speechSynthesis' in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='id-ID';u.rate=.88;u.pitch=1.06;speechSynthesis.speak(u)}catch{}}
  function tone(kind){if(!state.audio)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type='sine';o.frequency.value=kind==='ok'?660:kind==='bad'?180:420;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.05,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+(kind==='ok'?.28:.15));o.start();o.stop(c.currentTime+.3)}catch{}}
  const shuffle=a=>[...a].sort(()=>Math.random()-.5);
  function mascot(){return `<svg class="mascot" viewBox="0 0 120 120" role="img" aria-label="Mimi"><circle cx="60" cy="63" r="42" fill="#d9b48d"/><circle cx="30" cy="34" r="17" fill="#c89b70"/><circle cx="90" cy="34" r="17" fill="#c89b70"/><circle cx="44" cy="59" r="5" fill="#3f4039"/><circle cx="76" cy="59" r="5" fill="#3f4039"/><ellipse cx="60" cy="73" rx="14" ry="10" fill="#f1d7b7"/><circle cx="60" cy="70" r="4" fill="#70574a"/><path d="M52 79 Q60 87 68 79" fill="none" stroke="#70574a" stroke-width="3" stroke-linecap="round"/></svg>`}
  function top(){return `<div class="top"><button class="icon-btn" id="back" aria-label="Kembali">‹</button><div class="rounds">${Array.from({length:state.total},(_,i)=>`<i class="dot ${i<state.round?'done':''} ${i===state.round?'current':''}"></i>`).join('')}</div><button class="icon-btn" id="audio" aria-label="Suara">${state.audio?'🔊':'🔇'}</button></div>`}
  function visual(item,world){
    if(world==='animals') return `<img class="visual" src="${ASSET+item.img}" alt="${item.name}" draggable="false">`;
    if(world==='fruits') return `<div class="visual" aria-label="${item.name}" style="font-size:66px">${item.emoji}</div>`;
    const shapes={circle:'<circle cx="50" cy="50" r="34" fill="#9fc4d4"/>',square:'<rect x="17" y="17" width="66" height="66" rx="8" fill="#e7aaa1"/>',triangle:'<path d="M50 13 L88 84 H12 Z" fill="#f2cf75"/>',star:'<path d="M50 8 L61 37 L92 39 L68 58 L75 88 L50 71 L25 88 L32 58 L8 39 L39 37 Z" fill="#a9c9d6"/>',rectangle:'<rect x="10" y="28" width="80" height="44" rx="9" fill="#86a878"/>',heart:'<path d="M50 88 C12 62 8 40 22 26 C32 16 45 20 50 31 C55 20 68 16 78 26 C92 40 88 62 50 88Z" fill="#e7aaa1"/>'};
    return `<svg class="visual" viewBox="0 0 100 100" role="img" aria-label="${item.name}">${shapes[item.type]}</svg>`;
  }
  function home(){state.screen='home';state.world=null;state.activity=null;APP.innerHTML=`<div class="app"><div class="shell screen-fade"><section class="home">${mascot()}<h1 class="title">Teman Main</h1><p class="subtitle">Tempat kecil untuk bermain, menemukan, dan mengenal dunia dengan cara yang menyenangkan.</p><div class="worlds">${WORLDS.map(w=>`<button class="world" data-world="${w.id}"><div class="world-icon">${w.icon}</div><div><strong>${w.name}</strong><span>${w.desc}</span></div><b class="badge">›</b></button>`).join('')}</div><p class="parent-note">Tidak ada iklan, chat, leaderboard, atau infinite scroll.</p></section></div></div>`;APP.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>world(b.dataset.world));speak('Halo, teman! Yuk pilih dunia untuk bermain.')}
  function world(id){state.screen='world';state.world=id;const w=WORLDS.find(x=>x.id===id);APP.innerHTML=`<div class="app"><div class="shell screen-fade"><div class="top"><button class="icon-btn" id="back">‹</button><div style="flex:1"></div><button class="icon-btn" id="audio">${state.audio?'🔊':'🔇'}</button></div><section class="home">${mascot()}<h1 class="title">${w.name}</h1><p class="subtitle">${w.desc} Pilih permainan yang ingin dicoba.</p><div class="activities">${ACTIVITIES[id].map(a=>`<button class="activity" data-activity="${a[0]}"><div class="activity-icon">${a[3]}</div><div><strong>${a[1]}</strong><span>${a[2]}</span></div><b class="badge">›</b></button>`).join('')}</div></section></div></div>`;APP.querySelector('#back').onclick=home;APP.querySelector('#audio').onclick=toggleAudio;APP.querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>intro(id,b.dataset.activity));}
  function intro(worldId,activity){state.world=worldId;state.activity=activity;const meta=ACTIVITIES[worldId].find(a=>a[0]===activity);APP.innerHTML=`<div class="app"><div class="shell screen-fade"><div class="top"><button class="icon-btn" id="back">‹</button><div style="flex:1"></div><button class="icon-btn" id="audio">${state.audio?'🔊':'🔇'}</button></div><section class="intro">${mascot()}<h1 class="title">${meta[1]}</h1><p class="subtitle">${meta[2]}</p><button class="primary" id="start">Mulai bermain</button></section></div></div>`;APP.querySelector('#back').onclick=()=>world(worldId);APP.querySelector('#audio').onclick=toggleAudio;APP.querySelector('#start').onclick=()=>startGame();speak(meta[1]+'. '+meta[2])}
  function toggleAudio(){state.audio=!state.audio;saveAudio();if(!state.audio&&'speechSynthesis' in window)speechSynthesis.cancel();renderCurrent(false)}
  function startGame(){state.screen='play';state.round=0;state.locked=false;state.selected=null;state.matched=[];nextRound(true)}
  function nextRound(announce){state.locked=false;state.selected=null;state.matched=[];const list=DATA[state.world];state.target=list[Math.floor(Math.random()*list.length)];state.options=shuffle([state.target,...shuffle(list.filter(x=>x.id!==state.target.id)).slice(0,2)]);renderFind();if(announce){speak('Mana '+state.target.name.toLowerCase()+'?')} }
  function renderFind(){APP.innerHTML=`<div class="app"><div class="shell screen-fade">${top()}<section class="scene"><div class="sun"></div><div class="cloud a">☁</div><div class="cloud b">☁</div>${mascot()}<div class="question">Mana ${state.target.name.toLowerCase()}?</div><div class="hint">Sentuh yang benar.</div><div class="choices">${state.options.map(x=>`<button class="choice" data-id="${x.id}">${visual(x,state.world)}<span class="choice-label">${x.name}</span></button>`).join('')}</div><div class="feedback" id="feedback" aria-live="polite"></div></section></div></div>`;wireTop();APP.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answerFind(b.dataset.id,b));}
  function answerFind(id,btn){if(state.locked)return;state.locked=true;const ok=id===state.target.id;APP.querySelectorAll('.choice').forEach(b=>b.disabled=true);const f=APP.querySelector('#feedback');if(ok){btn.classList.add('pop');f.textContent='Hebat!';tone('ok');const extra=state.world==='animals'?state.target.sound:'Ini '+state.target.name.toLowerCase()+'.';speak('Hebat! '+extra);setTimeout(()=>{state.round++;if(state.round>=state.total)complete();else nextRound(true)},850)}else{btn.classList.add('wiggle');f.className='feedback bad';f.textContent='Yuk coba lagi.';tone('bad');speak('Yuk coba lagi.');setTimeout(()=>{state.locked=false;APP.querySelectorAll('.choice').forEach(b=>b.disabled=false)},600)}}
  function startMatch(){state.screen='match';state.round=0;state.locked=false;state.selected=null;state.matched=[];renderMatch();speak('Ayo pasangkan yang sama.')}
  function renderMatch(){const list=shuffle(DATA[state.world]).slice(0,3);const cards=shuffle([...list,...list.map(x=>({...x,copy:true}))]);state.matchCards=cards;state.matchPairs=Object.fromEntries(list.map(x=>[x.id,0]));APP.innerHTML=`<div class="app"><div class="shell screen-fade">${top()}<section class="scene"><div class="sun"></div>${mascot()}<div class="question">Pasangkan yang sama</div><div class="hint">Sentuh dua gambar yang sama.</div><div class="match-grid">${cards.map((x,i)=>`<button class="match-card" data-i="${i}">${visual(x,state.world)}</button>`).join('')}</div><div class="feedback" id="feedback" aria-live="polite"></div></section></div></div>`;wireTop();APP.querySelectorAll('.match-card').forEach(b=>b.onclick=()=>matchTap(Number(b.dataset.i)));}
  function matchTap(i){if(state.locked||state.matched.includes(i))return;const cards=state.matchCards;const btn=APP.querySelector(`[data-i="${i}"]`);if(state.selected===null){state.selected=i;btn.classList.add('selected');tone('tap');return}const prev=state.selected;const prevBtn=APP.querySelector(`[data-i="${prev}"]`);state.selected=null;prevBtn.classList.remove('selected');if(cards[prev].id===cards[i].id){btn.classList.add('matched');prevBtn.classList.add('matched');state.matched.push(prev,i);tone('ok');speak('Hebat! Sama.');if(state.matched.length===cards.length){state.round++;setTimeout(()=>complete(),650)}}else{state.locked=true;btn.classList.add('wiggle');prevBtn.classList.add('wiggle');tone('bad');speak('Belum sama. Yuk coba lagi.');setTimeout(()=>{btn.classList.remove('wiggle');prevBtn.classList.remove('wiggle');state.locked=false},500)}}
  function complete(){state.screen='complete';APP.innerHTML=`<div class="app"><div class="shell screen-fade"><section class="complete">${mascot()}<div class="stars">⭐ ⭐ ⭐</div><h2>Hebat!</h2><p>Kamu sudah menyelesaikan permainan.</p><div class="actions"><button class="secondary" id="world">Pilih permainan</button><button class="primary" id="again">Main lagi</button></div></section></div></div>`;tone('ok');speak('Hebat! Permainan selesai.');APP.querySelector('#world').onclick=()=>world(state.world);APP.querySelector('#again').onclick=()=>state.activity==='find'?startGame():startMatch()}
  function wireTop(){APP.querySelector('#back').onclick=()=>world(state.world);APP.querySelector('#audio').onclick=toggleAudio}
  function renderCurrent(){if(state.screen==='play')renderFind();else if(state.screen==='match')renderMatch();else if(state.screen==='world')world(state.world);else if(state.screen==='intro')intro(state.world,state.activity);else home()}
  const oldStartGame=startGame;
  startGame=()=>state.activity==='match'?startMatch():oldStartGame();
  home();
})();